//
//  https://timezonedb.com/
//
//  Creative Commons Attribution 3.0 License
//

window.tzData = {
    "+02":[
        "Europe/Ulyanovsk"
    ],
    "+03":[
        "Europe/Astrakhan",
        "Europe/Kirov",
        "Europe/Ulyanovsk"
    ],
    "+04":[
        "Asia/Aqtau",
        "Asia/Aqtobe",
        "Asia/Oral",
        "Asia/Qyzylorda",
        "Europe/Astrakhan",
        "Europe/Kirov",
        "Europe/Ulyanovsk"
    ],
    "+05":[
        "Asia/Almaty",
        "Asia/Aqtau",
        "Asia/Aqtobe",
        "Asia/Oral",
        "Asia/Qyzylorda",
        "Europe/Astrakhan",
        "Europe/Kirov",
        "Europe/Ulyanovsk"
    ],
    "+06":[
        "Asia/Almaty",
        "Asia/Aqtau",
        "Asia/Aqtobe",
        "Asia/Barnaul",
        "Asia/Novokuznetsk",
        "Asia/Novosibirsk",
        "Asia/Oral",
        "Asia/Qyzylorda",
        "Asia/Tomsk"
    ],
    "+07":[
        "Asia/Almaty",
        "Asia/Barnaul",
        "Asia/Novokuznetsk",
        "Asia/Novosibirsk",
        "Asia/Tomsk"
    ],
    "+08":[
        "Asia/Barnaul",
        "Asia/Novokuznetsk",
        "Asia/Novosibirsk",
        "Asia/Tomsk"
    ],
    "ACDT":[
        "Australia/Adelaide",
        "Australia/Broken_Hill",
        "Australia/Darwin"
    ],
    "ACST":[
        "America/Eirunepe",
        "America/Rio_Branco",
        "Asia/Jayapura",
        "Australia/Adelaide",
        "Australia/Broken_Hill",
        "Australia/Darwin"
    ],
    "ACT":[
        "America/Eirunepe",
        "America/Rio_Branco"
    ],
    "ACWDT":[
        "Australia/Eucla"
    ],
    "ACWST":[
        "Australia/Eucla"
    ],
    "ADDT":[
        "America/Goose_Bay",
        "America/Pangnirtung"
    ],
    "ADT":[
        "America/Barbados",
        "America/Blanc-Sablon",
        "America/Glace_Bay",
        "America/Goose_Bay",
        "America/Halifax",
        "America/Martinique",
        "America/Moncton",
        "America/Pangnirtung",
        "America/Thule",
        "Asia/Baghdad",
        "Atlantic/Bermuda"
    ],
    "AEDT":[
        "Antarctica/Macquarie",
        "Australia/Brisbane",
        "Australia/Currie",
        "Australia/Hobart",
        "Australia/Lindeman",
        "Australia/Melbourne",
        "Australia/Sydney"
    ],
    "AEST":[
        "Antarctica/Macquarie",
        "Australia/Brisbane",
        "Australia/Broken_Hill",
        "Australia/Currie",
        "Australia/Hobart",
        "Australia/Lindeman",
        "Australia/Lord_Howe",
        "Australia/Melbourne",
        "Australia/Sydney"
    ],
    "AFT":[
        "Asia/Kabul"
    ],
    "AHDT":[
        "America/Anchorage"
    ],
    "AHST":[
        "America/Adak",
        "America/Anchorage"
    ],
    "AKDT":[
        "America/Anchorage",
        "America/Juneau",
        "America/Metlakatla",
        "America/Nome",
        "America/Sitka",
        "America/Yakutat"
    ],
    "AKST":[
        "America/Anchorage",
        "America/Juneau",
        "America/Metlakatla",
        "America/Nome",
        "America/Sitka",
        "America/Yakutat"
    ],
    "AMST":[
        "America/Boa_Vista",
        "America/Campo_Grande",
        "America/Cuiaba",
        "America/Manaus",
        "America/Porto_Velho",
        "America/Santarem",
        "Asia/Yerevan"
    ],
    "AMT":[
        "America/Asuncion",
        "America/Boa_Vista",
        "America/Campo_Grande",
        "America/Cuiaba",
        "America/Eirunepe",
        "America/Manaus",
        "America/Porto_Velho",
        "America/Rio_Branco",
        "America/Santarem",
        "Asia/Yerevan",
        "Europe/Amsterdam",
        "Europe/Athens"
    ],
    "ANAST":[
        "Asia/Anadyr"
    ],
    "ANAT":[
        "Asia/Anadyr"
    ],
    "ANT":[
        "America/Aruba",
        "America/Curacao",
        "America/Kralendijk",
        "America/Lower_Princes"
    ],
    "APT":[
        "America/Blanc-Sablon",
        "America/Glace_Bay",
        "America/Halifax",
        "America/Moncton",
        "America/Pangnirtung",
        "America/Puerto_Rico"
    ],
    "ARST":[
        "America/Argentina/Buenos_Aires",
        "America/Argentina/Catamarca",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia",
        "Antarctica/Palmer"
    ],
    "ART":[
        "America/Argentina/Buenos_Aires",
        "America/Argentina/Catamarca",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia",
        "Antarctica/Palmer"
    ],
    "ASHST":[
        "Asia/Ashgabat"
    ],
    "ASHT":[
        "Asia/Ashgabat"
    ],
    "AST":[
        "America/Anguilla",
        "America/Antigua",
        "America/Aruba",
        "America/Barbados",
        "America/Blanc-Sablon",
        "America/Curacao",
        "America/Dominica",
        "America/Glace_Bay",
        "America/Goose_Bay",
        "America/Grand_Turk",
        "America/Grenada",
        "America/Guadeloupe",
        "America/Halifax",
        "America/Kralendijk",
        "America/Lower_Princes",
        "America/Marigot",
        "America/Martinique",
        "America/Miquelon",
        "America/Moncton",
        "America/Montserrat",
        "America/Pangnirtung",
        "America/Port_of_Spain",
        "America/Puerto_Rico",
        "America/Santo_Domingo",
        "America/St_Barthelemy",
        "America/St_Kitts",
        "America/St_Lucia",
        "America/St_Thomas",
        "America/St_Vincent",
        "America/Thule",
        "America/Tortola",
        "Asia/Aden",
        "Asia/Baghdad",
        "Asia/Bahrain",
        "Asia/Kuwait",
        "Asia/Qatar",
        "Asia/Riyadh",
        "Atlantic/Bermuda"
    ],
    "AWDT":[
        "Australia/Perth"
    ],
    "AWST":[
        "Antarctica/Casey",
        "Australia/Perth"
    ],
    "AWT":[
        "America/Blanc-Sablon",
        "America/Glace_Bay",
        "America/Halifax",
        "America/Moncton",
        "America/Pangnirtung",
        "America/Puerto_Rico"
    ],
    "AZOMT":[
        "Atlantic/Azores"
    ],
    "AZOST":[
        "Atlantic/Azores"
    ],
    "AZOT":[
        "Atlantic/Azores"
    ],
    "AZST":[
        "Asia/Baku"
    ],
    "AZT":[
        "Asia/Baku"
    ],
    "BAKST":[
        "Asia/Baku"
    ],
    "BAKT":[
        "Asia/Baku"
    ],
    "BDST":[
        "Asia/Dhaka",
        "Europe/Gibraltar",
        "Europe/Guernsey",
        "Europe/Isle_of_Man",
        "Europe/Jersey",
        "Europe/London"
    ],
    "BDT":[
        "America/Adak",
        "America/Nome",
        "Asia/Dhaka"
    ],
    "BEAT":[
        "Africa/Addis_Ababa",
        "Africa/Asmara",
        "Africa/Dar_es_Salaam",
        "Africa/Djibouti",
        "Africa/Kampala",
        "Africa/Mogadishu",
        "Africa/Nairobi",
        "Indian/Antananarivo",
        "Indian/Comoro",
        "Indian/Mayotte"
    ],
    "BEAUT":[
        "Africa/Addis_Ababa",
        "Africa/Asmara",
        "Africa/Dar_es_Salaam",
        "Africa/Djibouti",
        "Africa/Kampala",
        "Africa/Mogadishu",
        "Africa/Nairobi",
        "Indian/Antananarivo",
        "Indian/Comoro",
        "Indian/Mayotte"
    ],
    "BMT":[
        "America/Barbados",
        "America/Bogota",
        "Asia/Baghdad",
        "Asia/Bangkok",
        "Asia/Jakarta",
        "Asia/Phnom_Penh",
        "Asia/Vientiane",
        "Europe/Brussels",
        "Europe/Bucharest",
        "Europe/Busingen",
        "Europe/Chisinau",
        "Europe/Vaduz",
        "Europe/Zurich"
    ],
    "BNT":[
        "Asia/Brunei"
    ],
    "BORT":[
        "Asia/Kuching"
    ],
    "BORTST":[
        "Asia/Kuching"
    ],
    "BOST":[
        "America/La_Paz"
    ],
    "BOT":[
        "America/La_Paz"
    ],
    "BRST":[
        "America/Araguaina",
        "America/Bahia",
        "America/Belem",
        "America/Fortaleza",
        "America/Maceio",
        "America/Recife",
        "America/Sao_Paulo"
    ],
    "BRT":[
        "America/Araguaina",
        "America/Bahia",
        "America/Belem",
        "America/Fortaleza",
        "America/Maceio",
        "America/Recife",
        "America/Santarem",
        "America/Sao_Paulo"
    ],
    "BST":[
        "America/Adak",
        "America/Nome",
        "Europe/Dublin",
        "Europe/Gibraltar",
        "Europe/Guernsey",
        "Europe/Isle_of_Man",
        "Europe/Jersey",
        "Europe/London",
        "Pacific/Bougainville",
        "Pacific/Midway",
        "Pacific/Pago_Pago"
    ],
    "BTT":[
        "Asia/Thimphu"
    ],
    "BURT":[
        "Asia/Dhaka",
        "Asia/Kolkata",
        "Asia/Rangoon"
    ],
    "CANT":[
        "Atlantic/Canary"
    ],
    "CAPT":[
        "America/Anchorage"
    ],
    "CAST":[
        "Africa/Juba",
        "Africa/Khartoum",
        "Antarctica/Casey"
    ],
    "CAT":[
        "Africa/Blantyre",
        "Africa/Bujumbura",
        "Africa/Gaborone",
        "Africa/Harare",
        "Africa/Juba",
        "Africa/Khartoum",
        "Africa/Kigali",
        "Africa/Lubumbashi",
        "Africa/Lusaka",
        "Africa/Maputo",
        "Africa/Windhoek",
        "America/Anchorage"
    ],
    "CAWT":[
        "America/Anchorage"
    ],
    "CCT":[
        "Indian/Cocos"
    ],
    "CDDT":[
        "America/Rankin_Inlet",
        "America/Resolute"
    ],
    "CDT":[
        "America/Atikokan",
        "America/Bahia_Banderas",
        "America/Belize",
        "America/Cambridge_Bay",
        "America/Cancun",
        "America/Chicago",
        "America/Chihuahua",
        "America/Costa_Rica",
        "America/El_Salvador",
        "America/Guatemala",
        "America/Havana",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Iqaluit",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Managua",
        "America/Matamoros",
        "America/Menominee",
        "America/Merida",
        "America/Mexico_City",
        "America/Monterrey",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Ojinaga",
        "America/Pangnirtung",
        "America/Rainy_River",
        "America/Rankin_Inlet",
        "America/Resolute",
        "America/Tegucigalpa",
        "America/Winnipeg",
        "Asia/Shanghai",
        "Asia/Taipei"
    ],
    "CEMT":[
        "Europe/Berlin"
    ],
    "CEST":[
        "Africa/Algiers",
        "Africa/Ceuta",
        "Africa/Tripoli",
        "Africa/Tunis",
        "Antarctica/Troll",
        "Arctic/Longyearbyen",
        "Europe/Amsterdam",
        "Europe/Andorra",
        "Europe/Athens",
        "Europe/Belgrade",
        "Europe/Berlin",
        "Europe/Bratislava",
        "Europe/Brussels",
        "Europe/Budapest",
        "Europe/Busingen",
        "Europe/Chisinau",
        "Europe/Copenhagen",
        "Europe/Gibraltar",
        "Europe/Kaliningrad",
        "Europe/Kiev",
        "Europe/Lisbon",
        "Europe/Ljubljana",
        "Europe/Luxembourg",
        "Europe/Madrid",
        "Europe/Malta",
        "Europe/Minsk",
        "Europe/Monaco",
        "Europe/Oslo",
        "Europe/Paris",
        "Europe/Podgorica",
        "Europe/Prague",
        "Europe/Riga",
        "Europe/Rome",
        "Europe/San_Marino",
        "Europe/Sarajevo",
        "Europe/Simferopol",
        "Europe/Skopje",
        "Europe/Sofia",
        "Europe/Stockholm",
        "Europe/Tallinn",
        "Europe/Tirane",
        "Europe/Uzhgorod",
        "Europe/Vaduz",
        "Europe/Vatican",
        "Europe/Vienna",
        "Europe/Vilnius",
        "Europe/Warsaw",
        "Europe/Zagreb",
        "Europe/Zaporozhye",
        "Europe/Zurich"
    ],
    "CET":[
        "Africa/Algiers",
        "Africa/Casablanca",
        "Africa/Ceuta",
        "Africa/Tripoli",
        "Africa/Tunis",
        "Arctic/Longyearbyen",
        "Europe/Amsterdam",
        "Europe/Andorra",
        "Europe/Athens",
        "Europe/Belgrade",
        "Europe/Berlin",
        "Europe/Bratislava",
        "Europe/Brussels",
        "Europe/Budapest",
        "Europe/Busingen",
        "Europe/Chisinau",
        "Europe/Copenhagen",
        "Europe/Gibraltar",
        "Europe/Kaliningrad",
        "Europe/Kiev",
        "Europe/Lisbon",
        "Europe/Ljubljana",
        "Europe/Luxembourg",
        "Europe/Madrid",
        "Europe/Malta",
        "Europe/Minsk",
        "Europe/Monaco",
        "Europe/Oslo",
        "Europe/Paris",
        "Europe/Podgorica",
        "Europe/Prague",
        "Europe/Riga",
        "Europe/Rome",
        "Europe/San_Marino",
        "Europe/Sarajevo",
        "Europe/Simferopol",
        "Europe/Skopje",
        "Europe/Sofia",
        "Europe/Stockholm",
        "Europe/Tallinn",
        "Europe/Tirane",
        "Europe/Uzhgorod",
        "Europe/Vaduz",
        "Europe/Vatican",
        "Europe/Vienna",
        "Europe/Vilnius",
        "Europe/Warsaw",
        "Europe/Zagreb",
        "Europe/Zaporozhye",
        "Europe/Zurich"
    ],
    "CGST":[
        "America/Scoresbysund"
    ],
    "CGT":[
        "America/Scoresbysund"
    ],
    "CHADT":[
        "Pacific/Chatham"
    ],
    "CHAST":[
        "Pacific/Chatham"
    ],
    "CHDT":[
        "America/Belize"
    ],
    "CHOST":[
        "Asia/Choibalsan"
    ],
    "CHOT":[
        "Asia/Choibalsan"
    ],
    "CHUT":[
        "Pacific/Chuuk"
    ],
    "CKHST":[
        "Pacific/Rarotonga"
    ],
    "CKT":[
        "Pacific/Rarotonga"
    ],
    "CLST":[
        "America/Santiago",
        "Antarctica/Palmer"
    ],
    "CLT":[
        "America/Santiago",
        "Antarctica/Palmer"
    ],
    "CMT":[
        "America/Argentina/Buenos_Aires",
        "America/Argentina/Catamarca",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia",
        "America/Caracas",
        "America/Cayman",
        "America/La_Paz",
        "America/Panama",
        "Europe/Chisinau",
        "Europe/Copenhagen"
    ],
    "COST":[
        "America/Bogota"
    ],
    "COT":[
        "America/Bogota"
    ],
    "CPT":[
        "America/Atikokan",
        "America/Chicago",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Menominee",
        "America/Rainy_River",
        "America/Winnipeg"
    ],
    "CST":[
        "America/Atikokan",
        "America/Bahia_Banderas",
        "America/Belize",
        "America/Cambridge_Bay",
        "America/Cancun",
        "America/Chicago",
        "America/Chihuahua",
        "America/Costa_Rica",
        "America/Detroit",
        "America/El_Salvador",
        "America/Guatemala",
        "America/Havana",
        "America/Hermosillo",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Iqaluit",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Managua",
        "America/Matamoros",
        "America/Mazatlan",
        "America/Menominee",
        "America/Merida",
        "America/Mexico_City",
        "America/Monterrey",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Ojinaga",
        "America/Pangnirtung",
        "America/Rainy_River",
        "America/Rankin_Inlet",
        "America/Regina",
        "America/Resolute",
        "America/Swift_Current",
        "America/Tegucigalpa",
        "America/Thunder_Bay",
        "America/Winnipeg",
        "Asia/Macau",
        "Asia/Shanghai",
        "Asia/Taipei"
    ],
    "CUT":[
        "Europe/Zaporozhye"
    ],
    "CVST":[
        "Atlantic/Cape_Verde"
    ],
    "CVT":[
        "Atlantic/Cape_Verde"
    ],
    "CWT":[
        "America/Atikokan",
        "America/Chicago",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Menominee",
        "America/Mexico_City",
        "America/Rainy_River",
        "America/Winnipeg"
    ],
    "CXT":[
        "Indian/Christmas"
    ],
    "ChST":[
        "Pacific/Guam",
        "Pacific/Saipan"
    ],
    "DACT":[
        "Asia/Dhaka"
    ],
    "DAVT":[
        "Antarctica/Davis"
    ],
    "DDUT":[
        "Antarctica/DumontDUrville"
    ],
    "DMT":[
        "Europe/Dublin"
    ],
    "DUSST":[
        "Asia/Dushanbe"
    ],
    "DUST":[
        "Asia/Dushanbe"
    ],
    "EASST":[
        "Pacific/Easter"
    ],
    "EAST":[
        "Pacific/Easter"
    ],
    "EAT":[
        "Africa/Addis_Ababa",
        "Africa/Asmara",
        "Africa/Dar_es_Salaam",
        "Africa/Djibouti",
        "Africa/Juba",
        "Africa/Kampala",
        "Africa/Khartoum",
        "Africa/Mogadishu",
        "Africa/Nairobi",
        "Indian/Antananarivo",
        "Indian/Comoro",
        "Indian/Mayotte"
    ],
    "ECT":[
        "America/Guayaquil",
        "Pacific/Galapagos"
    ],
    "EDDT":[
        "America/Iqaluit"
    ],
    "EDT":[
        "America/Cancun",
        "America/Detroit",
        "America/Grand_Turk",
        "America/Indiana/Indianapolis",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Iqaluit",
        "America/Jamaica",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Nassau",
        "America/New_York",
        "America/Nipigon",
        "America/Pangnirtung",
        "America/Port-au-Prince",
        "America/Santo_Domingo",
        "America/Thunder_Bay",
        "America/Toronto"
    ],
    "EEST":[
        "Africa/Cairo",
        "Asia/Amman",
        "Asia/Beirut",
        "Asia/Damascus",
        "Asia/Gaza",
        "Asia/Hebron",
        "Asia/Nicosia",
        "Europe/Athens",
        "Europe/Bucharest",
        "Europe/Chisinau",
        "Europe/Helsinki",
        "Europe/Istanbul",
        "Europe/Kaliningrad",
        "Europe/Kiev",
        "Europe/Mariehamn",
        "Europe/Minsk",
        "Europe/Moscow",
        "Europe/Riga",
        "Europe/Samara",
        "Europe/Simferopol",
        "Europe/Sofia",
        "Europe/Tallinn",
        "Europe/Uzhgorod",
        "Europe/Vilnius",
        "Europe/Warsaw",
        "Europe/Zaporozhye"
    ],
    "EET":[
        "Africa/Cairo",
        "Africa/Tripoli",
        "Asia/Amman",
        "Asia/Beirut",
        "Asia/Damascus",
        "Asia/Gaza",
        "Asia/Hebron",
        "Asia/Nicosia",
        "Europe/Athens",
        "Europe/Bucharest",
        "Europe/Chisinau",
        "Europe/Helsinki",
        "Europe/Istanbul",
        "Europe/Kaliningrad",
        "Europe/Kiev",
        "Europe/Mariehamn",
        "Europe/Minsk",
        "Europe/Moscow",
        "Europe/Riga",
        "Europe/Simferopol",
        "Europe/Sofia",
        "Europe/Tallinn",
        "Europe/Uzhgorod",
        "Europe/Vilnius",
        "Europe/Warsaw",
        "Europe/Zaporozhye"
    ],
    "EGST":[
        "America/Scoresbysund"
    ],
    "EGT":[
        "America/Scoresbysund"
    ],
    "EHDT":[
        "America/Santo_Domingo"
    ],
    "EMT":[
        "Pacific/Easter"
    ],
    "EPT":[
        "America/Detroit",
        "America/Iqaluit",
        "America/New_York",
        "America/Nipigon",
        "America/Thunder_Bay",
        "America/Toronto"
    ],
    "EST":[
        "America/Atikokan",
        "America/Cambridge_Bay",
        "America/Cancun",
        "America/Cayman",
        "America/Chicago",
        "America/Detroit",
        "America/Grand_Turk",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Iqaluit",
        "America/Jamaica",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Managua",
        "America/Menominee",
        "America/Merida",
        "America/Moncton",
        "America/Nassau",
        "America/New_York",
        "America/Nipigon",
        "America/Panama",
        "America/Pangnirtung",
        "America/Port-au-Prince",
        "America/Rankin_Inlet",
        "America/Resolute",
        "America/Santo_Domingo",
        "America/Thunder_Bay",
        "America/Toronto"
    ],
    "EWT":[
        "America/Detroit",
        "America/Iqaluit",
        "America/New_York",
        "America/Nipigon",
        "America/Thunder_Bay",
        "America/Toronto"
    ],
    "FET":[
        "Europe/Kaliningrad",
        "Europe/Minsk"
    ],
    "FFMT":[
        "America/Martinique"
    ],
    "FJST":[
        "Pacific/Fiji"
    ],
    "FJT":[
        "Pacific/Fiji"
    ],
    "FKST":[
        "Atlantic/Stanley"
    ],
    "FKT":[
        "Atlantic/Stanley"
    ],
    "FMT":[
        "Atlantic/Madeira"
    ],
    "FNST":[
        "America/Noronha"
    ],
    "FNT":[
        "America/Noronha"
    ],
    "FRUST":[
        "Asia/Bishkek"
    ],
    "FRUT":[
        "Asia/Bishkek"
    ],
    "GALT":[
        "Pacific/Galapagos"
    ],
    "GAMT":[
        "Pacific/Gambier"
    ],
    "GBGT":[
        "America/Guyana"
    ],
    "GEST":[
        "Asia/Tbilisi"
    ],
    "GET":[
        "Asia/Tbilisi"
    ],
    "GFT":[
        "America/Cayenne"
    ],
    "GHST":[
        "Africa/Accra"
    ],
    "GILT":[
        "Pacific/Tarawa"
    ],
    "GMT":[
        "Africa/Abidjan",
        "Africa/Accra",
        "Africa/Bamako",
        "Africa/Banjul",
        "Africa/Bissau",
        "Africa/Conakry",
        "Africa/Dakar",
        "Africa/Freetown",
        "Africa/Lome",
        "Africa/Monrovia",
        "Africa/Nouakchott",
        "Africa/Ouagadougou",
        "Africa/Sao_Tome",
        "America/Danmarkshavn",
        "Atlantic/Reykjavik",
        "Atlantic/St_Helena",
        "Europe/Dublin",
        "Europe/Gibraltar",
        "Europe/Guernsey",
        "Europe/Isle_of_Man",
        "Europe/Jersey",
        "Europe/London"
    ],
    "GST":[
        "Asia/Bahrain",
        "Asia/Dubai",
        "Asia/Muscat",
        "Asia/Qatar",
        "Atlantic/South_Georgia",
        "Pacific/Guam",
        "Pacific/Saipan"
    ],
    "GYT":[
        "America/Guyana"
    ],
    "HDT":[
        "America/Adak",
        "Pacific/Honolulu",
        "Pacific/Johnston"
    ],
    "HKST":[
        "Asia/Hong_Kong"
    ],
    "HKT":[
        "Asia/Hong_Kong"
    ],
    "HMT":[
        "America/Havana",
        "Asia/Dhaka",
        "Asia/Kolkata",
        "Atlantic/Azores",
        "Europe/Helsinki",
        "Europe/Mariehamn"
    ],
    "HOVST":[
        "Asia/Hovd"
    ],
    "HOVT":[
        "Asia/Hovd"
    ],
    "HST":[
        "America/Adak",
        "Pacific/Honolulu",
        "Pacific/Johnston"
    ],
    "ICT":[
        "Asia/Bangkok",
        "Asia/Ho_Chi_Minh",
        "Asia/Phnom_Penh",
        "Asia/Vientiane"
    ],
    "IDDT":[
        "Asia/Jerusalem"
    ],
    "IDT":[
        "Asia/Gaza",
        "Asia/Hebron",
        "Asia/Ho_Chi_Minh",
        "Asia/Jerusalem"
    ],
    "IHST":[
        "Asia/Colombo"
    ],
    "IMT":[
        "Asia/Irkutsk",
        "Europe/Istanbul",
        "Europe/Sofia"
    ],
    "IOT":[
        "Indian/Chagos"
    ],
    "IRDT":[
        "Asia/Tehran"
    ],
    "IRKST":[
        "Asia/Irkutsk"
    ],
    "IRKT":[
        "Asia/Chita",
        "Asia/Irkutsk"
    ],
    "IRST":[
        "Asia/Tehran"
    ],
    "ISST":[
        "Atlantic/Reykjavik"
    ],
    "IST":[
        "Asia/Colombo",
        "Asia/Dhaka",
        "Asia/Gaza",
        "Asia/Hebron",
        "Asia/Jerusalem",
        "Asia/Karachi",
        "Asia/Kathmandu",
        "Asia/Kolkata",
        "Asia/Thimphu",
        "Atlantic/Reykjavik",
        "Europe/Dublin"
    ],
    "JAVT":[
        "Asia/Jakarta"
    ],
    "JCST":[
        "Asia/Pyongyang",
        "Asia/Sakhalin",
        "Asia/Seoul",
        "Asia/Tokyo"
    ],
    "JDT":[
        "Asia/Tokyo"
    ],
    "JMT":[
        "Asia/Jerusalem"
    ],
    "JST":[
        "Asia/Dili",
        "Asia/Ho_Chi_Minh",
        "Asia/Hong_Kong",
        "Asia/Jakarta",
        "Asia/Kuala_Lumpur",
        "Asia/Kuching",
        "Asia/Makassar",
        "Asia/Manila",
        "Asia/Pontianak",
        "Asia/Pyongyang",
        "Asia/Rangoon",
        "Asia/Sakhalin",
        "Asia/Seoul",
        "Asia/Singapore",
        "Asia/Taipei",
        "Asia/Tokyo",
        "Pacific/Bougainville",
        "Pacific/Nauru"
    ],
    "JWST":[
        "Asia/Taipei"
    ],
    "KART":[
        "Asia/Karachi"
    ],
    "KDT":[
        "Asia/Seoul"
    ],
    "KGST":[
        "Asia/Bishkek"
    ],
    "KGT":[
        "Asia/Bishkek"
    ],
    "KMT":[
        "America/Grand_Turk",
        "America/Jamaica",
        "Europe/Kiev",
        "Europe/Vilnius"
    ],
    "KOST":[
        "Pacific/Kosrae"
    ],
    "KRAST":[
        "Asia/Krasnoyarsk"
    ],
    "KRAT":[
        "Asia/Krasnoyarsk"
    ],
    "KST":[
        "Asia/Pyongyang",
        "Asia/Seoul"
    ],
    "KUYST":[
        "Europe/Samara"
    ],
    "KUYT":[
        "Europe/Samara"
    ],
    "KWAT":[
        "Pacific/Kwajalein"
    ],
    "LHDT":[
        "Australia/Lord_Howe"
    ],
    "LHST":[
        "Australia/Lord_Howe"
    ],
    "LINT":[
        "Pacific/Kiritimati"
    ],
    "LKT":[
        "Asia/Colombo"
    ],
    "LMT":[
        "Africa/Abidjan",
        "Africa/Accra",
        "Africa/Addis_Ababa",
        "Africa/Algiers",
        "Africa/Asmara",
        "Africa/Bamako",
        "Africa/Bangui",
        "Africa/Banjul",
        "Africa/Bissau",
        "Africa/Blantyre",
        "Africa/Brazzaville",
        "Africa/Bujumbura",
        "Africa/Cairo",
        "Africa/Casablanca",
        "Africa/Ceuta",
        "Africa/Conakry",
        "Africa/Dakar",
        "Africa/Dar_es_Salaam",
        "Africa/Djibouti",
        "Africa/Douala",
        "Africa/El_Aaiun",
        "Africa/Freetown",
        "Africa/Gaborone",
        "Africa/Harare",
        "Africa/Johannesburg",
        "Africa/Juba",
        "Africa/Kampala",
        "Africa/Khartoum",
        "Africa/Kigali",
        "Africa/Kinshasa",
        "Africa/Lagos",
        "Africa/Libreville",
        "Africa/Lome",
        "Africa/Luanda",
        "Africa/Lubumbashi",
        "Africa/Lusaka",
        "Africa/Malabo",
        "Africa/Maputo",
        "Africa/Maseru",
        "Africa/Mbabane",
        "Africa/Mogadishu",
        "Africa/Monrovia",
        "Africa/Nairobi",
        "Africa/Ndjamena",
        "Africa/Niamey",
        "Africa/Nouakchott",
        "Africa/Ouagadougou",
        "Africa/Porto-Novo",
        "Africa/Sao_Tome",
        "Africa/Tripoli",
        "Africa/Tunis",
        "Africa/Windhoek",
        "America/Adak",
        "America/Anchorage",
        "America/Anguilla",
        "America/Antigua",
        "America/Araguaina",
        "America/Argentina/Buenos_Aires",
        "America/Argentina/Catamarca",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia",
        "America/Aruba",
        "America/Asuncion",
        "America/Atikokan",
        "America/Bahia",
        "America/Bahia_Banderas",
        "America/Barbados",
        "America/Belem",
        "America/Belize",
        "America/Blanc-Sablon",
        "America/Boa_Vista",
        "America/Bogota",
        "America/Boise",
        "America/Campo_Grande",
        "America/Cancun",
        "America/Caracas",
        "America/Cayenne",
        "America/Cayman",
        "America/Chicago",
        "America/Chihuahua",
        "America/Costa_Rica",
        "America/Creston",
        "America/Cuiaba",
        "America/Curacao",
        "America/Danmarkshavn",
        "America/Dawson",
        "America/Dawson_Creek",
        "America/Denver",
        "America/Detroit",
        "America/Dominica",
        "America/Edmonton",
        "America/Eirunepe",
        "America/El_Salvador",
        "America/Fort_Nelson",
        "America/Fortaleza",
        "America/Glace_Bay",
        "America/Godthab",
        "America/Goose_Bay",
        "America/Grand_Turk",
        "America/Grenada",
        "America/Guadeloupe",
        "America/Guatemala",
        "America/Guayaquil",
        "America/Guyana",
        "America/Halifax",
        "America/Havana",
        "America/Hermosillo",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Jamaica",
        "America/Juneau",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Kralendijk",
        "America/La_Paz",
        "America/Lima",
        "America/Los_Angeles",
        "America/Lower_Princes",
        "America/Maceio",
        "America/Managua",
        "America/Manaus",
        "America/Marigot",
        "America/Martinique",
        "America/Matamoros",
        "America/Mazatlan",
        "America/Menominee",
        "America/Merida",
        "America/Metlakatla",
        "America/Mexico_City",
        "America/Miquelon",
        "America/Moncton",
        "America/Monterrey",
        "America/Montevideo",
        "America/Montserrat",
        "America/Nassau",
        "America/New_York",
        "America/Nipigon",
        "America/Nome",
        "America/Noronha",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Ojinaga",
        "America/Panama",
        "America/Paramaribo",
        "America/Phoenix",
        "America/Port-au-Prince",
        "America/Port_of_Spain",
        "America/Porto_Velho",
        "America/Puerto_Rico",
        "America/Rainy_River",
        "America/Recife",
        "America/Regina",
        "America/Rio_Branco",
        "America/Santarem",
        "America/Santiago",
        "America/Santo_Domingo",
        "America/Sao_Paulo",
        "America/Scoresbysund",
        "America/Sitka",
        "America/St_Barthelemy",
        "America/St_Johns",
        "America/St_Kitts",
        "America/St_Lucia",
        "America/St_Thomas",
        "America/St_Vincent",
        "America/Swift_Current",
        "America/Tegucigalpa",
        "America/Thule",
        "America/Thunder_Bay",
        "America/Tijuana",
        "America/Toronto",
        "America/Tortola",
        "America/Vancouver",
        "America/Whitehorse",
        "America/Winnipeg",
        "America/Yakutat",
        "Antarctica/McMurdo",
        "Arctic/Longyearbyen",
        "Asia/Aden",
        "Asia/Almaty",
        "Asia/Amman",
        "Asia/Anadyr",
        "Asia/Aqtau",
        "Asia/Aqtobe",
        "Asia/Ashgabat",
        "Asia/Baghdad",
        "Asia/Bahrain",
        "Asia/Baku",
        "Asia/Bangkok",
        "Asia/Barnaul",
        "Asia/Beirut",
        "Asia/Bishkek",
        "Asia/Brunei",
        "Asia/Chita",
        "Asia/Choibalsan",
        "Asia/Colombo",
        "Asia/Damascus",
        "Asia/Dhaka",
        "Asia/Dili",
        "Asia/Dubai",
        "Asia/Dushanbe",
        "Asia/Gaza",
        "Asia/Hebron",
        "Asia/Ho_Chi_Minh",
        "Asia/Hong_Kong",
        "Asia/Hovd",
        "Asia/Irkutsk",
        "Asia/Jakarta",
        "Asia/Jayapura",
        "Asia/Jerusalem",
        "Asia/Kabul",
        "Asia/Kamchatka",
        "Asia/Karachi",
        "Asia/Kathmandu",
        "Asia/Khandyga",
        "Asia/Kolkata",
        "Asia/Krasnoyarsk",
        "Asia/Kuala_Lumpur",
        "Asia/Kuching",
        "Asia/Kuwait",
        "Asia/Macau",
        "Asia/Magadan",
        "Asia/Makassar",
        "Asia/Manila",
        "Asia/Muscat",
        "Asia/Nicosia",
        "Asia/Novokuznetsk",
        "Asia/Novosibirsk",
        "Asia/Omsk",
        "Asia/Oral",
        "Asia/Phnom_Penh",
        "Asia/Pontianak",
        "Asia/Pyongyang",
        "Asia/Qatar",
        "Asia/Qyzylorda",
        "Asia/Rangoon",
        "Asia/Riyadh",
        "Asia/Sakhalin",
        "Asia/Samarkand",
        "Asia/Seoul",
        "Asia/Shanghai",
        "Asia/Singapore",
        "Asia/Srednekolymsk",
        "Asia/Taipei",
        "Asia/Tashkent",
        "Asia/Tbilisi",
        "Asia/Tehran",
        "Asia/Thimphu",
        "Asia/Tokyo",
        "Asia/Tomsk",
        "Asia/Ulaanbaatar",
        "Asia/Urumqi",
        "Asia/Ust-Nera",
        "Asia/Vientiane",
        "Asia/Vladivostok",
        "Asia/Yakutsk",
        "Asia/Yekaterinburg",
        "Asia/Yerevan",
        "Atlantic/Azores",
        "Atlantic/Bermuda",
        "Atlantic/Canary",
        "Atlantic/Cape_Verde",
        "Atlantic/Faroe",
        "Atlantic/Madeira",
        "Atlantic/Reykjavik",
        "Atlantic/South_Georgia",
        "Atlantic/St_Helena",
        "Atlantic/Stanley",
        "Australia/Adelaide",
        "Australia/Brisbane",
        "Australia/Broken_Hill",
        "Australia/Currie",
        "Australia/Darwin",
        "Australia/Eucla",
        "Australia/Hobart",
        "Australia/Lindeman",
        "Australia/Lord_Howe",
        "Australia/Melbourne",
        "Australia/Perth",
        "Australia/Sydney",
        "Europe/Amsterdam",
        "Europe/Andorra",
        "Europe/Astrakhan",
        "Europe/Athens",
        "Europe/Belgrade",
        "Europe/Berlin",
        "Europe/Bratislava",
        "Europe/Brussels",
        "Europe/Bucharest",
        "Europe/Budapest",
        "Europe/Busingen",
        "Europe/Chisinau",
        "Europe/Copenhagen",
        "Europe/Dublin",
        "Europe/Gibraltar",
        "Europe/Guernsey",
        "Europe/Helsinki",
        "Europe/Isle_of_Man",
        "Europe/Istanbul",
        "Europe/Jersey",
        "Europe/Kaliningrad",
        "Europe/Kiev",
        "Europe/Kirov",
        "Europe/Lisbon",
        "Europe/Ljubljana",
        "Europe/London",
        "Europe/Luxembourg",
        "Europe/Madrid",
        "Europe/Malta",
        "Europe/Mariehamn",
        "Europe/Minsk",
        "Europe/Monaco",
        "Europe/Moscow",
        "Europe/Oslo",
        "Europe/Paris",
        "Europe/Podgorica",
        "Europe/Prague",
        "Europe/Riga",
        "Europe/Rome",
        "Europe/Samara",
        "Europe/San_Marino",
        "Europe/Sarajevo",
        "Europe/Simferopol",
        "Europe/Skopje",
        "Europe/Sofia",
        "Europe/Stockholm",
        "Europe/Tallinn",
        "Europe/Tirane",
        "Europe/Ulyanovsk",
        "Europe/Uzhgorod",
        "Europe/Vaduz",
        "Europe/Vatican",
        "Europe/Vienna",
        "Europe/Vilnius",
        "Europe/Volgograd",
        "Europe/Warsaw",
        "Europe/Zagreb",
        "Europe/Zaporozhye",
        "Europe/Zurich",
        "Indian/Antananarivo",
        "Indian/Chagos",
        "Indian/Christmas",
        "Indian/Cocos",
        "Indian/Comoro",
        "Indian/Mahe",
        "Indian/Maldives",
        "Indian/Mauritius",
        "Indian/Mayotte",
        "Indian/Reunion",
        "Pacific/Apia",
        "Pacific/Auckland",
        "Pacific/Bougainville",
        "Pacific/Chatham",
        "Pacific/Chuuk",
        "Pacific/Easter",
        "Pacific/Efate",
        "Pacific/Enderbury",
        "Pacific/Fakaofo",
        "Pacific/Fiji",
        "Pacific/Funafuti",
        "Pacific/Galapagos",
        "Pacific/Gambier",
        "Pacific/Guadalcanal",
        "Pacific/Guam",
        "Pacific/Honolulu",
        "Pacific/Johnston",
        "Pacific/Kiritimati",
        "Pacific/Kosrae",
        "Pacific/Kwajalein",
        "Pacific/Majuro",
        "Pacific/Marquesas",
        "Pacific/Midway",
        "Pacific/Nauru",
        "Pacific/Niue",
        "Pacific/Norfolk",
        "Pacific/Noumea",
        "Pacific/Pago_Pago",
        "Pacific/Palau",
        "Pacific/Pitcairn",
        "Pacific/Pohnpei",
        "Pacific/Port_Moresby",
        "Pacific/Rarotonga",
        "Pacific/Saipan",
        "Pacific/Tahiti",
        "Pacific/Tarawa",
        "Pacific/Tongatapu",
        "Pacific/Wake",
        "Pacific/Wallis"
    ],
    "LRT":[
        "Africa/Monrovia"
    ],
    "LST":[
        "Europe/Riga"
    ],
    "MADMT":[
        "Atlantic/Madeira"
    ],
    "MADST":[
        "Atlantic/Madeira"
    ],
    "MADT":[
        "Atlantic/Madeira"
    ],
    "MAGST":[
        "Asia/Magadan",
        "Asia/Srednekolymsk",
        "Asia/Ust-Nera"
    ],
    "MAGT":[
        "Asia/Magadan",
        "Asia/Srednekolymsk",
        "Asia/Ust-Nera"
    ],
    "MALST":[
        "Asia/Kuala_Lumpur",
        "Asia/Singapore"
    ],
    "MALT":[
        "Asia/Kuala_Lumpur",
        "Asia/Singapore"
    ],
    "MART":[
        "Pacific/Marquesas"
    ],
    "MAWT":[
        "Antarctica/Mawson"
    ],
    "MDDT":[
        "America/Cambridge_Bay",
        "America/Yellowknife"
    ],
    "MDST":[
        "Europe/Moscow"
    ],
    "MDT":[
        "America/Bahia_Banderas",
        "America/Boise",
        "America/Cambridge_Bay",
        "America/Chihuahua",
        "America/Denver",
        "America/Edmonton",
        "America/Hermosillo",
        "America/Inuvik",
        "America/Mazatlan",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Ojinaga",
        "America/Phoenix",
        "America/Regina",
        "America/Swift_Current",
        "America/Yellowknife"
    ],
    "MHT":[
        "Pacific/Kwajalein",
        "Pacific/Majuro"
    ],
    "MIST":[
        "Antarctica/Macquarie"
    ],
    "MMT":[
        "Africa/Monrovia",
        "America/Managua",
        "America/Montevideo",
        "Asia/Colombo",
        "Asia/Makassar",
        "Asia/Rangoon",
        "Europe/Minsk",
        "Europe/Moscow",
        "Indian/Maldives"
    ],
    "MOST":[
        "Asia/Macau"
    ],
    "MOT":[
        "Asia/Macau"
    ],
    "MPT":[
        "America/Boise",
        "America/Cambridge_Bay",
        "America/Denver",
        "America/Edmonton",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Regina",
        "America/Swift_Current",
        "America/Yellowknife"
    ],
    "MSD":[
        "Europe/Chisinau",
        "Europe/Kaliningrad",
        "Europe/Kiev",
        "Europe/Minsk",
        "Europe/Moscow",
        "Europe/Riga",
        "Europe/Samara",
        "Europe/Simferopol",
        "Europe/Tallinn",
        "Europe/Uzhgorod",
        "Europe/Vilnius",
        "Europe/Volgograd",
        "Europe/Zaporozhye"
    ],
    "MSK":[
        "Europe/Chisinau",
        "Europe/Kaliningrad",
        "Europe/Kiev",
        "Europe/Minsk",
        "Europe/Moscow",
        "Europe/Riga",
        "Europe/Samara",
        "Europe/Simferopol",
        "Europe/Tallinn",
        "Europe/Uzhgorod",
        "Europe/Vilnius",
        "Europe/Volgograd",
        "Europe/Zaporozhye"
    ],
    "MSM":[
        "Europe/Moscow"
    ],
    "MST":[
        "America/Bahia_Banderas",
        "America/Boise",
        "America/Cambridge_Bay",
        "America/Chihuahua",
        "America/Creston",
        "America/Dawson_Creek",
        "America/Denver",
        "America/Edmonton",
        "America/Fort_Nelson",
        "America/Hermosillo",
        "America/Inuvik",
        "America/Mazatlan",
        "America/Mexico_City",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Ojinaga",
        "America/Phoenix",
        "America/Regina",
        "America/Swift_Current",
        "America/Tijuana",
        "America/Yellowknife",
        "Europe/Moscow"
    ],
    "MUST":[
        "Indian/Mauritius"
    ],
    "MUT":[
        "Indian/Mauritius"
    ],
    "MVT":[
        "Indian/Maldives"
    ],
    "MWT":[
        "America/Boise",
        "America/Cambridge_Bay",
        "America/Denver",
        "America/Edmonton",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Phoenix",
        "America/Regina",
        "America/Swift_Current",
        "America/Yellowknife"
    ],
    "MYT":[
        "Asia/Kuala_Lumpur",
        "Asia/Kuching"
    ],
    "NCST":[
        "Pacific/Noumea"
    ],
    "NCT":[
        "Pacific/Noumea"
    ],
    "NDDT":[
        "America/St_Johns"
    ],
    "NDT":[
        "America/Goose_Bay",
        "America/St_Johns"
    ],
    "NEGT":[
        "America/Paramaribo"
    ],
    "NEST":[
        "Europe/Amsterdam"
    ],
    "NET":[
        "Europe/Amsterdam"
    ],
    "NFST":[
        "Pacific/Norfolk"
    ],
    "NFT":[
        "Pacific/Norfolk"
    ],
    "NMT":[
        "Pacific/Norfolk"
    ],
    "NPT":[
        "America/Adak",
        "America/Goose_Bay",
        "America/Nome",
        "America/St_Johns",
        "Asia/Kathmandu"
    ],
    "NRT":[
        "Pacific/Nauru"
    ],
    "NST":[
        "America/Adak",
        "America/Goose_Bay",
        "America/Nome",
        "America/St_Johns",
        "Europe/Amsterdam",
        "Pacific/Midway",
        "Pacific/Pago_Pago"
    ],
    "NUT":[
        "Pacific/Niue"
    ],
    "NWT":[
        "America/Adak",
        "America/Goose_Bay",
        "America/Nome",
        "America/St_Johns"
    ],
    "NZDT":[
        "Antarctica/McMurdo",
        "Pacific/Auckland"
    ],
    "NZMT":[
        "Antarctica/McMurdo",
        "Pacific/Auckland"
    ],
    "NZST":[
        "Antarctica/McMurdo",
        "Pacific/Auckland"
    ],
    "OMSST":[
        "Asia/Omsk"
    ],
    "OMST":[
        "Asia/Omsk"
    ],
    "PDDT":[
        "America/Inuvik"
    ],
    "PDT":[
        "America/Boise",
        "America/Dawson",
        "America/Dawson_Creek",
        "America/Fort_Nelson",
        "America/Juneau",
        "America/Los_Angeles",
        "America/Metlakatla",
        "America/Sitka",
        "America/Tijuana",
        "America/Vancouver",
        "America/Whitehorse"
    ],
    "PEST":[
        "America/Lima"
    ],
    "PET":[
        "America/Lima"
    ],
    "PETST":[
        "Asia/Kamchatka"
    ],
    "PETT":[
        "Asia/Kamchatka"
    ],
    "PGT":[
        "Pacific/Bougainville",
        "Pacific/Port_Moresby"
    ],
    "PHOT":[
        "Pacific/Enderbury"
    ],
    "PHST":[
        "Asia/Manila"
    ],
    "PHT":[
        "Asia/Manila"
    ],
    "PKST":[
        "Asia/Karachi"
    ],
    "PKT":[
        "Asia/Karachi"
    ],
    "PLMT":[
        "Asia/Ho_Chi_Minh"
    ],
    "PMDT":[
        "America/Miquelon"
    ],
    "PMMT":[
        "Pacific/Bougainville",
        "Pacific/Port_Moresby"
    ],
    "PMST":[
        "America/Miquelon"
    ],
    "PMT":[
        "Africa/Algiers",
        "Africa/Tunis",
        "America/Paramaribo",
        "Antarctica/DumontDUrville",
        "Asia/Pontianak",
        "Asia/Yekaterinburg",
        "Europe/Bratislava",
        "Europe/Monaco",
        "Europe/Paris",
        "Europe/Prague"
    ],
    "PNT":[
        "Pacific/Pitcairn"
    ],
    "PONT":[
        "Pacific/Pohnpei"
    ],
    "PPMT":[
        "America/Port-au-Prince"
    ],
    "PPT":[
        "America/Dawson_Creek",
        "America/Fort_Nelson",
        "America/Juneau",
        "America/Los_Angeles",
        "America/Metlakatla",
        "America/Sitka",
        "America/Tijuana",
        "America/Vancouver"
    ],
    "PST":[
        "America/Bahia_Banderas",
        "America/Boise",
        "America/Creston",
        "America/Dawson",
        "America/Dawson_Creek",
        "America/Fort_Nelson",
        "America/Hermosillo",
        "America/Inuvik",
        "America/Juneau",
        "America/Los_Angeles",
        "America/Mazatlan",
        "America/Metlakatla",
        "America/Sitka",
        "America/Tijuana",
        "America/Vancouver",
        "America/Whitehorse",
        "Pacific/Pitcairn"
    ],
    "PWT":[
        "America/Dawson_Creek",
        "America/Fort_Nelson",
        "America/Juneau",
        "America/Los_Angeles",
        "America/Metlakatla",
        "America/Sitka",
        "America/Tijuana",
        "America/Vancouver",
        "Pacific/Palau"
    ],
    "PYST":[
        "America/Asuncion"
    ],
    "PYT":[
        "America/Asuncion"
    ],
    "QMT":[
        "America/Guayaquil"
    ],
    "RET":[
        "Indian/Reunion"
    ],
    "RMT":[
        "Asia/Rangoon",
        "Europe/Riga",
        "Europe/Rome",
        "Europe/San_Marino",
        "Europe/Vatican"
    ],
    "ROTT":[
        "Antarctica/Rothera"
    ],
    "SAKST":[
        "Asia/Sakhalin"
    ],
    "SAKT":[
        "Asia/Sakhalin"
    ],
    "SAMST":[
        "Asia/Samarkand",
        "Europe/Samara"
    ],
    "SAMT":[
        "Asia/Samarkand",
        "Europe/Samara"
    ],
    "SAST":[
        "Africa/Johannesburg",
        "Africa/Maseru",
        "Africa/Mbabane",
        "Africa/Windhoek"
    ],
    "SBT":[
        "Pacific/Guadalcanal"
    ],
    "SCT":[
        "Indian/Mahe"
    ],
    "SDMT":[
        "America/Santo_Domingo"
    ],
    "SDT":[
        "Pacific/Apia"
    ],
    "SET":[
        "Europe/Stockholm"
    ],
    "SGT":[
        "Asia/Singapore"
    ],
    "SJMT":[
        "America/Costa_Rica"
    ],
    "SMT":[
        "America/Santiago",
        "Asia/Kuala_Lumpur",
        "Asia/Singapore",
        "Atlantic/Stanley",
        "Europe/Simferopol"
    ],
    "SRET":[
        "Asia/Srednekolymsk"
    ],
    "SRT":[
        "America/Paramaribo"
    ],
    "SST":[
        "Pacific/Apia",
        "Pacific/Midway",
        "Pacific/Pago_Pago"
    ],
    "STAT":[
        "Europe/Volgograd"
    ],
    "SVEST":[
        "Asia/Yekaterinburg"
    ],
    "SVET":[
        "Asia/Yekaterinburg"
    ],
    "SWAT":[
        "Africa/Windhoek"
    ],
    "SYOT":[
        "Antarctica/Syowa"
    ],
    "TAHT":[
        "Pacific/Tahiti"
    ],
    "TASST":[
        "Asia/Tashkent"
    ],
    "TAST":[
        "Asia/Samarkand",
        "Asia/Tashkent"
    ],
    "TBIST":[
        "Asia/Tbilisi"
    ],
    "TBIT":[
        "Asia/Tbilisi"
    ],
    "TBMT":[
        "Asia/Tbilisi"
    ],
    "TFT":[
        "Indian/Kerguelen"
    ],
    "TJT":[
        "Asia/Dushanbe"
    ],
    "TKT":[
        "Pacific/Fakaofo"
    ],
    "TLT":[
        "Asia/Dili"
    ],
    "TMT":[
        "Asia/Ashgabat",
        "Asia/Tehran",
        "Europe/Tallinn"
    ],
    "TOST":[
        "Pacific/Tongatapu"
    ],
    "TOT":[
        "Pacific/Tongatapu"
    ],
    "TRST":[
        "Europe/Istanbul"
    ],
    "TRT":[
        "Europe/Istanbul"
    ],
    "TSAT":[
        "Europe/Volgograd"
    ],
    "TVT":[
        "Pacific/Funafuti"
    ],
    "ULAST":[
        "Asia/Ulaanbaatar"
    ],
    "ULAT":[
        "Asia/Choibalsan",
        "Asia/Ulaanbaatar"
    ],
    "UTC":[
        "Antarctica/Troll"
    ],
    "UYHST":[
        "America/Montevideo"
    ],
    "UYST":[
        "America/Montevideo"
    ],
    "UYT":[
        "America/Montevideo"
    ],
    "UZST":[
        "Asia/Samarkand",
        "Asia/Tashkent"
    ],
    "UZT":[
        "Asia/Samarkand",
        "Asia/Tashkent"
    ],
    "VET":[
        "America/Caracas"
    ],
    "VLAST":[
        "Asia/Khandyga",
        "Asia/Vladivostok"
    ],
    "VLAT":[
        "Asia/Khandyga",
        "Asia/Ust-Nera",
        "Asia/Vladivostok"
    ],
    "VOLST":[
        "Europe/Volgograd"
    ],
    "VOLT":[
        "Europe/Volgograd"
    ],
    "VOST":[
        "Antarctica/Vostok"
    ],
    "VUST":[
        "Pacific/Efate"
    ],
    "VUT":[
        "Pacific/Efate"
    ],
    "WAKT":[
        "Pacific/Wake"
    ],
    "WARST":[
        "America/Argentina/Jujuy",
        "America/Argentina/Mendoza",
        "America/Argentina/San_Luis"
    ],
    "WART":[
        "America/Argentina/Catamarca",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia"
    ],
    "WAST":[
        "Africa/Ndjamena",
        "Africa/Windhoek"
    ],
    "WAT":[
        "Africa/Bangui",
        "Africa/Bissau",
        "Africa/Brazzaville",
        "Africa/Douala",
        "Africa/El_Aaiun",
        "Africa/Kinshasa",
        "Africa/Lagos",
        "Africa/Libreville",
        "Africa/Luanda",
        "Africa/Malabo",
        "Africa/Ndjamena",
        "Africa/Niamey",
        "Africa/Porto-Novo",
        "Africa/Windhoek"
    ],
    "WEMT":[
        "Europe/Lisbon",
        "Europe/Madrid",
        "Europe/Monaco",
        "Europe/Paris"
    ],
    "WEST":[
        "Africa/Algiers",
        "Africa/Casablanca",
        "Africa/Ceuta",
        "Africa/El_Aaiun",
        "Atlantic/Canary",
        "Atlantic/Faroe",
        "Atlantic/Madeira",
        "Europe/Brussels",
        "Europe/Lisbon",
        "Europe/Luxembourg",
        "Europe/Madrid",
        "Europe/Monaco",
        "Europe/Paris"
    ],
    "WET":[
        "Africa/Algiers",
        "Africa/Casablanca",
        "Africa/Ceuta",
        "Africa/El_Aaiun",
        "Atlantic/Azores",
        "Atlantic/Canary",
        "Atlantic/Faroe",
        "Atlantic/Madeira",
        "Europe/Andorra",
        "Europe/Brussels",
        "Europe/Lisbon",
        "Europe/Luxembourg",
        "Europe/Madrid",
        "Europe/Monaco",
        "Europe/Paris"
    ],
    "WFT":[
        "Pacific/Wallis"
    ],
    "WGST":[
        "America/Danmarkshavn",
        "America/Godthab"
    ],
    "WGT":[
        "America/Danmarkshavn",
        "America/Godthab"
    ],
    "WIB":[
        "Asia/Jakarta",
        "Asia/Pontianak"
    ],
    "WITA":[
        "Asia/Dili",
        "Asia/Makassar",
        "Asia/Pontianak"
    ],
    "WIT":[
        "Asia/Jayapura"
    ],
    "WMT":[
        "Europe/Vilnius",
        "Europe/Warsaw"
    ],
    "WSDT":[
        "Pacific/Apia"
    ],
    "WSST":[
        "Pacific/Apia"
    ],
    "XJT":[
        "Asia/Urumqi"
    ],
    "YAKST":[
        "Asia/Chita",
        "Asia/Khandyga",
        "Asia/Yakutsk"
    ],
    "YAKT":[
        "Asia/Chita",
        "Asia/Khandyga",
        "Asia/Ust-Nera",
        "Asia/Yakutsk"
    ],
    "YDDT":[
        "America/Dawson",
        "America/Whitehorse"
    ],
    "YDT":[
        "America/Dawson",
        "America/Juneau",
        "America/Whitehorse",
        "America/Yakutat"
    ],
    "YEKST":[
        "Asia/Yekaterinburg"
    ],
    "YEKT":[
        "Asia/Yekaterinburg"
    ],
    "YERST":[
        "Asia/Yerevan"
    ],
    "YERT":[
        "Asia/Yerevan"
    ],
    "YPT":[
        "America/Dawson",
        "America/Whitehorse",
        "America/Yakutat"
    ],
    "YST":[
        "America/Anchorage",
        "America/Dawson",
        "America/Juneau",
        "America/Nome",
        "America/Sitka",
        "America/Whitehorse",
        "America/Yakutat"
    ],
    "YWT":[
        "America/Dawson",
        "America/Whitehorse",
        "America/Yakutat"
    ]
};